name: Create an issue
description: Creates a new issue using a template with front matter.
runs:
  using: docker
  image: Dockerfile
branding:
  icon: alert-circle
  color: gray-dark
inputs:
  assignees:
    description: GitHub handle of the user(s) to assign the issue (comma-separated)
  filename:
    description: The name of the file to use as the issue template
    default: .github/ISSUE_TEMPLATE.md
outputs:
  url:
    description: URL of the issue that was created
